# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Harikeshav
  pool: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production

